package org.kai.academy.signinservlet;

import java.io.*;

import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.*;
import jakarta.servlet.annotation.*;
import org.hibernate.Session;
import org.kai.academy.signinservlet.utils.HibernateUtil;

@WebServlet(name = "SignupServlet", value = "/signup")
public class SignupServlet extends HttpServlet {
    Session session = null;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<head>																																   ");
        out.println("    <meta charset=\"UTF-8\">                                                                                                          ");
        out.println("    <title>Signup</title>                                                                                                             ");
        out.println("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">           ");
        out.println("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>                                           ");
        out.println("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>                                             ");
        out.println("    <style>                                                                                                                           ");
        out.println("        .register {                                                                                                                   ");
        out.println("            background: -webkit-linear-gradient(left, #3931af, #00c6ff);                                                              ");
        out.println("            margin-top: 3%;                                                                                                           ");
        out.println("            padding: 3%;                                                                                                              ");
        out.println("        }                                                                                                                             ");
        out.println("        .register-left {                                                                                                              ");
        out.println("            text-align: center;                                                                                                       ");
        out.println("            color: #fff;                                                                                                              ");
        out.println("            margin-top: 4%;                                                                                                           ");
        out.println("        }                                                                                                                             ");
        out.println("        .register-left input {                                                                                                        ");
        out.println("            border: none;                                                                                                             ");
        out.println("            border-radius: 1.5rem;                                                                                                    ");
        out.println("            padding: 2%;                                                                                                              ");
        out.println("            width: 60%;                                                                                                               ");
        out.println("            background: #f8f9fa;                                                                                                      ");
        out.println("            font-weight: bold;                                                                                                        ");
        out.println("            color: #383d41;                                                                                                           ");
        out.println("            margin-top: 30%;                                                                                                          ");
        out.println("            margin-bottom: 3%;                                                                                                        ");
        out.println("            cursor: pointer;                                                                                                          ");
        out.println("        }                                                                                                                             ");
        out.println("        .register-right {                                                                                                             ");
        out.println("            background: #f8f9fa;                                                                                                      ");
        out.println("            border-top-left-radius: 10% 50%;                                                                                          ");
        out.println("            border-bottom-left-radius: 10% 50%;                                                                                       ");
        out.println("        }                                                                                                                             ");
        out.println("        .register-left img {                                                                                                          ");
        out.println("            margin-top: 15%;                                                                                                          ");
        out.println("            margin-bottom: 5%;                                                                                                        ");
        out.println("            width: 25%;                                                                                                               ");
        out.println("            -webkit-animation: mover 2s infinite alternate;                                                                           ");
        out.println("            animation: mover 1s infinite alternate;                                                                                   ");
        out.println("        }                                                                                                                             ");
        out.println("        @-webkit-keyframes mover {                                                                                                    ");
        out.println("            0% {                                                                                                                      ");
        out.println("                transform: translateY(0);                                                                                             ");
        out.println("            }                                                                                                                         ");
        out.println("            100% {                                                                                                                    ");
        out.println("                transform: translateY(-20px);                                                                                         ");
        out.println("            }                                                                                                                         ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        @keyframes mover {                                                                                                            ");
        out.println("            0% {                                                                                                                      ");
        out.println("                transform: translateY(0);                                                                                             ");
        out.println("            }                                                                                                                         ");
        out.println("            100% {                                                                                                                    ");
        out.println("                transform: translateY(-20px);                                                                                         ");
        out.println("            }                                                                                                                         ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register-left p {                                                                                                            ");
        out.println("            font-weight: lighter;                                                                                                     ");
        out.println("            padding: 12%;                                                                                                             ");
        out.println("            margin-top: -9%;                                                                                                          ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register .register-form {                                                                                                    ");
        out.println("            padding: 10%;                                                                                                             ");
        out.println("            margin-top: 10%;                                                                                                          ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .btnRegister {                                                                                                                ");
        out.println("            float: right;                                                                                                             ");
        out.println("            margin-top: 10%;                                                                                                          ");
        out.println("            border: none;                                                                                                             ");
        out.println("            border-radius: 1.5rem;                                                                                                    ");
        out.println("            padding: 2%;                                                                                                              ");
        out.println("            background: #0062cc;                                                                                                      ");
        out.println("            color: #fff;                                                                                                              ");
        out.println("            font-weight: 600;                                                                                                         ");
        out.println("            width: 50%;                                                                                                               ");
        out.println("            cursor: pointer;                                                                                                          ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register .nav-tabs {                                                                                                         ");
        out.println("            margin-top: 3%;                                                                                                           ");
        out.println("            border: none;                                                                                                             ");
        out.println("            background: #0062cc;                                                                                                      ");
        out.println("            border-radius: 1.5rem;                                                                                                    ");
        out.println("            width: 28%;                                                                                                               ");
        out.println("            float: right;                                                                                                             ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register .nav-tabs .nav-link {                                                                                               ");
        out.println("            padding: 2%;                                                                                                              ");
        out.println("            height: 34px;                                                                                                             ");
        out.println("            font-weight: 600;                                                                                                         ");
        out.println("            color: #fff;                                                                                                              ");
        out.println("            border-top-right-radius: 1.5rem;                                                                                          ");
        out.println("            border-bottom-right-radius: 1.5rem;                                                                                       ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register .nav-tabs .nav-link:hover {                                                                                         ");
        out.println("            border: none;                                                                                                             ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register .nav-tabs .nav-link.active {                                                                                        ");
        out.println("            width: 100px;                                                                                                             ");
        out.println("            color: #0062cc;                                                                                                           ");
        out.println("            border: 2px solid #0062cc;                                                                                                ");
        out.println("            border-top-left-radius: 1.5rem;                                                                                           ");
        out.println("            border-bottom-left-radius: 1.5rem;                                                                                        ");
        out.println("        }                                                                                                                             ");
        out.println("                                                                                                                                      ");
        out.println("        .register-heading {                                                                                                           ");
        out.println("            text-align: center;                                                                                                       ");
        out.println("            margin-top: 8%;                                                                                                           ");
        out.println("            margin-bottom: -15%;                                                                                                      ");
        out.println("            color: #495057;                                                                                                           ");
        out.println("        }                                                                                                                             ");
        out.println("    </style>                                                                                                                          ");
        out.println("</head>                                                                                                                               ");
        out.println("<body>                                                                                                                                ");
        out.println("<div class=\"container register\">                                                                                                    ");
        out.println("    <div class=\"row\">                                                                                                               ");
        out.println("        <div class=\"col-md-3 register-left\">                                                                                        ");
        out.println("            <img src=\"https://image.ibb.co/n7oTvU/logo_white.png\" alt=\"\"/>                                                        ");
        out.println("            <h3>Welcome</h3>                                                                                                          ");
        out.println("            <p>You are 30 seconds away from earning your own money!</p>                                                               ");
        out.println("            <input type=\"submit\" name=\"\" value=\"Login\"/><br/>                                                                   ");
        out.println("        </div>                                                                                                                        ");
        out.println("        <div class=\"col-md-9 register-right\">                                                                                       ");
        out.println("            <ul class=\"nav nav-tabs nav-justified\" id=\"myTab\" role=\"tablist\">                                                   ");
        out.println("                <li class=\"nav-item\">                                                                                               ");
        out.println("                    <a class=\"nav-link active\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\"                      ");
        out.println("                       aria-controls=\"home\" aria-selected=\"true\">Employee</a>                                                     ");
        out.println("                </li>                                                                                                                 ");
        out.println("                <li class=\"nav-item\">                                                                                               ");
        out.println("                    <a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\"                       ");
        out.println("                       aria-controls=\"profile\" aria-selected=\"false\">Hirer</a>                                                    ");
        out.println("                </li>                                                                                                                 ");
        out.println("            </ul>                                                                                                                     ");
        out.println("            <div class=\"tab-content\" id=\"myTabContent\">                                                                           ");
        out.println("                <div class=\"tab-pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">                  ");
        out.println("                    <h3 class=\"register-heading\">Apply as a Employee</h3>                                                           ");
        out.println("                    <div class=\"row register-form\">                                                                                 ");
        out.println("                        <div class=\"col-md-6\">                                                                                      ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"First Name *\" value=\"\"/>                 ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"Last Name *\" value=\"\"/>                  ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"password\" class=\"form-control\" placeholder=\"Password *\" value=\"\"/>               ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"password\" class=\"form-control\" placeholder=\"Confirm Password *\" value=\"\"/>       ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <div class=\"maxl\">                                                                                  ");
        out.println("                                    <label class=\"radio inline\">                                                                    ");
        out.println("                                        <input type=\"radio\" name=\"gender\" value=\"male\" checked>                                 ");
        out.println("                                        <span> Male </span>                                                                           ");
        out.println("                                    </label>                                                                                          ");
        out.println("                                    <label class=\"radio inline\">                                                                    ");
        out.println("                                        <input type=\"radio\" name=\"gender\" value=\"female\">                                       ");
        out.println("                                        <span>Female </span>                                                                          ");
        out.println("                                    </label>                                                                                          ");
        out.println("                                </div>                                                                                                ");
        out.println("                            </div>                                                                                                    ");
        out.println("                        </div>                                                                                                        ");
        out.println("                        <div class=\"col-md-6\">                                                                                      ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"email\" class=\"form-control\" placeholder=\"Your Email *\" value=\"\"/>                ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" minlength=\"10\" maxlength=\"10\" name=\"txtEmpPhone\" class=\"form-control\"    ");
        out.println("                                       placeholder=\"Your Phone *\" value=\"\"/>                                                      ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <select class=\"form-control\">                                                                       ");
        out.println("                                    <option class=\"hidden\" selected disabled>Please select your Sequrity Question                   ");
        out.println("                                    </option>                                                                                         ");
        out.println("                                    <option>What is your Birthdate?</option>                                                          ");
        out.println("                                    <option>What is Your old Phone Number</option>                                                    ");
        out.println("                                    <option>What is your Pet Name?</option>                                                           ");
        out.println("                                </select>                                                                                             ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"Enter Your Answer *\" value=\"\"/>          ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <input type=\"submit\" class=\"btnRegister\" value=\"Register\"/>                                         ");
        out.println("                        </div>                                                                                                        ");
        out.println("                    </div>                                                                                                            ");
        out.println("                </div>                                                                                                                ");
        out.println("                <div class=\"tab-pane fade show\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">                   ");
        out.println("                    <h3 class=\"register-heading\">Apply as a Hirer</h3>                                                              ");
        out.println("                    <div class=\"row register-form\">                                                                                 ");
        out.println("                        <div class=\"col-md-6\">                                                                                      ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"First Name *\" value=\"\"/>                 ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"Last Name *\" value=\"\"/>                  ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"email\" class=\"form-control\" placeholder=\"Email *\" value=\"\"/>                     ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" maxlength=\"10\" minlength=\"10\" class=\"form-control\"                         ");
        out.println("                                       placeholder=\"Phone *\" value=\"\"/>                                                           ");
        out.println("                            </div>                                                                                                    ");
        out.println("                                                                                                                                      ");
        out.println("                                                                                                                                      ");
        out.println("                        </div>                                                                                                        ");
        out.println("                        <div class=\"col-md-6\">                                                                                      ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"password\" class=\"form-control\" placeholder=\"Password *\" value=\"\"/>               ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"password\" class=\"form-control\" placeholder=\"Confirm Password *\" value=\"\"/>       ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <select class=\"form-control\">                                                                       ");
        out.println("                                    <option class=\"hidden\" selected disabled>Please select your Sequrity Question                   ");
        out.println("                                    </option>                                                                                         ");
        out.println("                                    <option>What is your Birthdate?</option>                                                          ");
        out.println("                                    <option>What is Your old Phone Number</option>                                                    ");
        out.println("                                    <option>What is your Pet Name?</option>                                                           ");
        out.println("                                </select>                                                                                             ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <div class=\"form-group\">                                                                                ");
        out.println("                                <input type=\"text\" class=\"form-control\" placeholder=\"`Answer *\" value=\"\"/>                    ");
        out.println("                            </div>                                                                                                    ");
        out.println("                            <input type=\"submit\" class=\"btnRegister\" value=\"Register\"/>                                         ");
        out.println("                        </div>                                                                                                        ");
        out.println("                    </div>                                                                                                            ");
        out.println("                </div>                                                                                                                ");
        out.println("            </div>                                                                                                                    ");
        out.println("        </div>                                                                                                                        ");
        out.println("    </div>                                                                                                                            ");
        out.println("</div>                                                                                                                                ");
        out.println("</body>                                                                                                                               ");
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }

    @Override
    public void init(ServletConfig config) throws ServletException {
        try {
            session = HibernateUtil.getSessionFactory().openSession();
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
}
